// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineRestaurant.Services.ProductAPI.Data;

#nullable disable

namespace OnlineRestaurant.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineRestaurant.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Fast Food",
                            Description = "Delicious cheese pizza",
                            Discount = 0,
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            Name = "Pizza",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Fast Food",
                            Description = "Juicy beef burger with lettuce and tomato",
                            Discount = 0,
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            Name = "Burger",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Italian",
                            Description = "Creamy Alfredo pasta with chicken",
                            Discount = 0,
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            Name = "Pasta",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Healthy",
                            Description = "Fresh garden salad with vinaigrette dressing",
                            Discount = 0,
                            ImageUrl = "https://picsum.photos/seed/picsum/200/300",
                            Name = "Salad",
                            Price = 7.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
